### PR TITLE
Allow GitHub Action to be run on-demand

### PR DESCRIPTION
**Pull request by cclauss**
Sometimes you just don't wanna wait until Wednesday...

Like https://github.com/internetarchive/openlibrary/actions/workflows/cron_watcher.yml ...
You will get a `Run workflow` button that will let you run anytime on any branch.

### CODE REVIEW

**Comment by RayBB** [comment]
Love it!

**Comment by cclauss** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

**Comment by cclauss** [comment]
Here is another on-demand GHA that I use to test remote repos.  Look at the most recent run to see why this repo failed the safety test. https://github.com/cclauss/itinerant-tester/actions/workflows/itinerant_tester_on_demand.yml

**Comment by cclauss** [comment]
Do you have a `Run workflow` button on https://github.com/RayBB/openlibrary-nyt-bot-temp/actions ?  I do not.

Screenshot 2022-06-06 at 16 19 23

**Comment by RayBB** [comment]
@cclauss I see it. You likely can't see it because you're not a collaborator. But I added you as one so you can play around with it if you like

**Comment by cclauss** [comment]
Yes.  I see it now.  It is good to understand the limits.

**Pull request merged**
